apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins-permanent
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkins-permanent
  template:
    metadata:
      labels:
        app: jenkins-permanent
    spec:
      securityContext:
        fsGroup: 1000
        runAsNonRoot: true
        runAsUser: 1000
      tolerations:
        - key: "node"
          operator: "Equal"
          value: "storage-ssd"
          effect: "NoSchedule"

      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: node
                    operator: In
                    values:
                      - storage-ssd
      containers:
      - name: jenkins-permanent
        image: jenkins/jenkins:lts
        ports:
          - name: http-port
            containerPort: 8080
          - name: jnlp-port
            containerPort: 50000
        volumeMounts:
          - name: jenkins-home
            mountPath: /var/jenkins_home
      volumes:
        - name: jenkins-home
          persistentVolumeClaim:
            claimName: jenkins-permanent