apiVersion: v1
kind: Service
metadata:
  name: jenkins-permanent
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30000
  selector:
    app: jenkins-permanent

---

apiVersion: v1
kind: Service
metadata:
  name: jenkins-permanent-jnlp
spec:
  type: ClusterIP
  ports:
    - port: 50000
      targetPort: 50000
  selector:
    app: jenkins-permanent