---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  labels:
    name: jenkins-permanent
  name: jenkins-permanent
spec:
  storageClassName: longhorn
  accessModes:
    - "ReadWriteOnce"
  resources:
    requests:
      storage: "8Gi"
      
      